# Generated by Django 3.2 on 2021-04-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20210412_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task',
            field=models.CharField(default='Task', max_length=250),
            preserve_default=False,
        ),
    ]
