# Generated by Django 3.2 on 2021-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_taskhistory_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
