# Generated by Django 3.2 on 2021-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_taskhistory_is_parent_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='spent_in_seconds',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
