# Generated by Django 3.2 on 2021-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_rename_spent_in_seconds_taskhistory_spent_in_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='is_done_approve',
            field=models.BooleanField(default=False),
        ),
    ]
