# Generated by Django 3.2 on 2021-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_taskhistory_is_done_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_remark',
            field=models.CharField(default='', max_length=150),
        ),
    ]
