# Generated by Django 3.2.2 on 2021-05-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_taskhistory_task_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='remark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
