# Generated by Django 3.2.2 on 2021-05-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_taskhistory_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='task_remark',
        ),
    ]
