# Generated by Django 3.2.1 on 2021-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_remove_taskhistory_task_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='change_tab_count',
            field=models.IntegerField(default=0),
        ),
    ]
