# Generated by Django 3.1.5 on 2021-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0002_remove_customuser_is_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_expiration',
            field=models.IntegerField(default=30),
        ),
    ]
