# Generated by Django 3.1.7 on 2021-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0003_auto_20210216_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='task_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='track_task',
            field=models.CharField(default='Blank', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
