# Generated by Django 3.1.7 on 2021-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0004_auto_20210402_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='track_task',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
