# Generated by Django 3.2 on 2021-04-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0007_customuser_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='previouspassword',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
