# Generated by Django 3.2 on 2021-04-10 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0009_auto_20210410_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_user_account_api_customuser_children_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
