# Generated by Django 3.2 on 2021-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0011_customuser_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approve_student',
            field=models.BooleanField(default=False),
        ),
    ]
