# Generated by Django 3.2 on 2021-04-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20210412_1010'),
        ('user_account_api', '0013_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
