# Generated by Django 3.2 on 2021-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0014_rename_subjects_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='track_subject_id',
            field=models.IntegerField(default=-1),
        ),
    ]
