# Generated by Django 3.2 on 2021-04-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0015_customuser_track_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user_account_api.customuser'),
            preserve_default=False,
        ),
    ]
