# Generated by Django 3.2.1 on 2021-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0017_alter_customuser_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='page_visible',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
