# Generated by Django 3.2.2 on 2021-07-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0018_customuser_page_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_set_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='task_limit',
            field=models.TimeField(default=None),
        ),
    ]
