# Generated by Django 3.2.2 on 2021-07-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_api', '0022_alter_subject_task_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='task_limit',
            field=models.DurationField(default=0, null=True),
        ),
    ]
